'use strict';
// Convert the rendered, sanitized document into native Word paragraphs and tables.
window.exportWord=async function(source,{title,paper='A4',margin=20}={}){
const D=window.docx;if(!D)throw Error('A biblioteca de Word não carregou. Reabra a página.');
const root=source.getElementById('document'),view=source.defaultView;
const warnings=new Set(),numbering=[];let listCounter=0;
const page=paper==='Letter'?{width:12240,height:15840}:{width:11906,height:16838};
const marginTwip=Math.round(margin/25.4*1440),availableWidth=page.width-2*marginTwip;
function color(value){if(!value||value==='transparent'||value==='rgba(0, 0, 0, 0)')return undefined;const match=value.match(/^rgba?\(\s*(\d+)[, ]+\s*(\d+)[, ]+\s*(\d+)/);if(match)return match.slice(1).map(n=>Math.min(255,Number(n)).toString(16).padStart(2,'0')).join('');if(/^#[\da-f]{6}$/i.test(value))return value.slice(1);return undefined;}
function style(el){return view.getComputedStyle(el.nodeType===1?el:el.parentElement||root);}
function fontFamily(value){const names=(value||'Arial').split(',').map(s=>s.trim().replace(/["']/g,''));const generic={'system-ui':'Arial','-apple-system':'Arial','BlinkMacSystemFont':'Arial','ui-monospace':'Consolas','monospace':'Consolas','sans-serif':'Arial','serif':'Georgia'};return generic[names[0]]||names[0]||'Arial';}
function luminance(hex){if(!hex)return 1;return (parseInt(hex.slice(0,2),16)*.2126+parseInt(hex.slice(2,4),16)*.7152+parseInt(hex.slice(4,6),16)*.0722)/255;}
const pageColor=color(style(root).backgroundColor)||color(style(source.body).backgroundColor)||'FFFFFF';const darkPage=luminance(pageColor)<.4;if(darkPage)warnings.add('Tema escuro adaptado para página branca no Word.');
function runStyle(node){const s=style(node),el=node.nodeType===1?node:node.parentElement;const bg=color(s.backgroundColor);let foreground=color(s.color)||'24292F';const surface=el?.closest('pre,td,th');const surfaceColor=surface&&(color(style(surface).backgroundColor)||color(style(surface.parentElement).backgroundColor));if(darkPage&&luminance(foreground)>.6&&!bg&&(!surfaceColor||luminance(surfaceColor)>.6))foreground='24292F';return{font:fontFamily(s.fontFamily),size:Math.max(12,Math.min(144,Math.round((parseFloat(s.fontSize)||16)*1.5))),color:foreground,bold:Number(s.fontWeight)>=600||s.fontWeight==='bold',italics:s.fontStyle==='italic',strike:s.textDecorationLine.includes('line-through')||!!el?.closest('del,s'),underline:s.textDecorationLine.includes('underline')?{type:D.UnderlineType.SINGLE}:undefined,shading:bg?{type:D.ShadingType.CLEAR,fill:bg}:undefined,subScript:!!el?.closest('sub'),superScript:!!el?.closest('sup')};}
async function image(node){try{const src=node.getAttribute('src')||'';if(!/^https:\/\/|^data:image\//i.test(src))throw Error('URL incompatível');const response=await fetch(src,{signal:AbortSignal.timeout(8000),credentials:'omit'});if(!response.ok)throw Error('Imagem indisponível');const blob=await response.blob();if(blob.size>10*1024*1024)throw Error('Imagem grande');const mime=blob.type.split(';')[0];let data=new Uint8Array(await blob.arrayBuffer());let type=({'image/png':'png','image/jpeg':'jpg','image/gif':'gif','image/bmp':'bmp'})[mime];let width=node.naturalWidth||480,height=node.naturalHeight||320;if(!type){const bitmap=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);const png=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!png)throw Error('Formato incompatível');data=new Uint8Array(await png.arrayBuffer());type='png';width=bitmap.width;height=bitmap.height;bitmap.close();}const limit=availableWidth/15;const ratio=Math.min(1,limit/width,780/height);return new D.ImageRun({type,data,transformation:{width:Math.round(width*ratio),height:Math.round(height*ratio)},altText:{title:node.alt||'Imagem',description:node.alt||'Imagem',name:node.alt||'Imagem'}});}catch{warnings.add('Algumas imagens foram substituídas pelo texto alternativo (URL, formato ou CORS).');return new D.TextRun({text:'[Imagem: '+(node.alt||node.getAttribute('src')||'indisponível')+']',italics:true});}}
async function inline(nodes,{pre=false}={}){const out=[];for(const node of nodes){if(node.nodeType===3){let text=node.textContent;if(!pre)text=text.replace(/\s+/g,' ');if(text)out.push(new D.TextRun({text,...runStyle(node)}));continue;}if(node.nodeType!==1)continue;const tag=node.tagName.toLowerCase();if(['ul','ol','table'].includes(tag))continue;if(tag==='br'){out.push(new D.TextRun({break:1}));continue;}if(tag==='img'){out.push(await image(node));continue;}if(tag==='input'){if(node.type==='checkbox')out.push(new D.TextRun({text:node.checked?'[x] ':'[ ] ',font:'Consolas'}));continue;}const children=await inline([...node.childNodes],{pre});if(tag==='a' && /^(https?:|mailto:)/i.test(node.getAttribute('href')||'')){out.push(new D.ExternalHyperlink({link:node.getAttribute('href'),children:children.length?children:[new D.TextRun(node.textContent)]}));}else out.push(...children);}return out;}
function alignmentOf(el){const textAlign=style(el).textAlign.replace(/^-webkit-/,'');return({center:D.AlignmentType.CENTER,right:D.AlignmentType.RIGHT,justify:D.AlignmentType.JUSTIFIED})[textAlign]||D.AlignmentType.LEFT;}
function pOptions(el){const s=style(el);return{alignment:alignmentOf(el),spacing:{before:Math.min(480,Math.max(0,Math.round((parseFloat(s.marginTop)||0)*15))),after:Math.min(480,Math.max(100,Math.round((parseFloat(s.marginBottom)||0)*15))),line:276},widowControl:true};}
async function paragraph(el,extra={}){return new D.Paragraph({...pOptions(el),...extra,children:await inline([...el.childNodes])});}
async function list(el,level=0){const result=[],ordered=el.tagName==='OL',reference='list-'+(++listCounter),start=Number(el.getAttribute('start'))||1;numbering.push({reference,levels:Array.from({length:9},(_,i)=>({level:i,format:ordered?D.LevelFormat.DECIMAL:D.LevelFormat.BULLET,text:ordered?'%'+(i+1)+'.':'•',alignment:D.AlignmentType.LEFT,start:i===Math.min(level,8)?start:1,style:{paragraph:{indent:{left:360*(i+1),hanging:240}}}}))});
for(const li of [...el.children].filter(n=>n.tagName==='LI')){const direct=[...li.childNodes].filter(n=>n.nodeType!==1||!['UL','OL','P','PRE','TABLE','BLOCKQUOTE'].includes(n.tagName));let hasParagraph=false;if(direct.some(n=>n.nodeType!==3||n.textContent.trim())){result.push(new D.Paragraph({...pOptions(li),numbering:{reference,level:Math.min(level,8)},children:await inline(direct),spacing:{after:90,line:276}}));hasParagraph=true;}for(const child of li.children){if(['UL','OL'].includes(child.tagName)){result.push(...await list(child,level+1));}else if(child.tagName==='P'){result.push(await paragraph(child,hasParagraph?{indent:{left:360*(level+1)}}:{numbering:{reference,level:Math.min(level,8)}}));hasParagraph=true;}else if(['PRE','TABLE','BLOCKQUOTE'].includes(child.tagName)){result.push(...await blocks([child],level+1));}}}return result;}
async function table(el){const rows=[...el.rows];const count=Math.max(1,...rows.map(r=>[...r.cells].reduce((s,c)=>s+(c.colSpan||1),0)));const width=Math.floor(availableWidth/count);const borders={top:{style:D.BorderStyle.SINGLE,size:4,color:'D9D9D9'},bottom:{style:D.BorderStyle.SINGLE,size:4,color:'D9D9D9'},left:{style:D.BorderStyle.SINGLE,size:4,color:'D9D9D9'},right:{style:D.BorderStyle.SINGLE,size:4,color:'D9D9D9'}};
const output=[];for(const row of rows){const cells=[];for(const cell of row.cells){let children=await blocks([...cell.childNodes],0,cell);if(!children.length)children=[new D.Paragraph('')];if(!(children.at(-1) instanceof D.Paragraph))children.push(new D.Paragraph(''));let fill=color(style(cell).backgroundColor)||color(style(row).backgroundColor);if(!fill&&cell.tagName==='TH')fill='F2F4F5';cells.push(new D.TableCell({children,width:{size:width*(cell.colSpan||1),type:D.WidthType.DXA},columnSpan:cell.colSpan>1?cell.colSpan:undefined,rowSpan:cell.rowSpan>1?cell.rowSpan:undefined,borders,margins:{top:100,bottom:100,left:120,right:120},verticalAlign:D.VerticalAlign.CENTER,shading:fill?{type:D.ShadingType.CLEAR,fill}:undefined}));}output.push(new D.TableRow({children:cells,tableHeader:row.parentElement?.tagName==='THEAD',cantSplit:true}));}return new D.Table({rows:output,width:{size:availableWidth,type:D.WidthType.DXA},columnWidths:Array(count).fill(width),layout:D.TableLayoutType.FIXED});}
async function blocks(nodes,depth=0,alignEl){const output=[],pending=[];async function flush(){if(!pending.length)return;const children=await inline(pending.splice(0));if(children.length)output.push(new D.Paragraph({children,alignment:alignEl?alignmentOf(alignEl):undefined,spacing:{after:140,line:276}}));}for(const node of nodes){if(node.nodeType===3){if(node.textContent.trim())pending.push(node);continue;}if(node.nodeType!==1)continue;const tag=node.tagName;if(!['P','H1','H2','H3','H4','H5','H6','UL','OL','TABLE','PRE','BLOCKQUOTE','HR','DIV','SECTION','ARTICLE','DL','DT','DD'].includes(tag)){pending.push(node);continue;}await flush();if(/^H[1-6]$/.test(tag)){output.push(await paragraph(node,{heading:D.HeadingLevel['HEADING_'+tag[1]],keepNext:true,spacing:{before:280,after:160,line:276}}));}else if(tag==='P'||tag==='DT'||tag==='DD'){output.push(await paragraph(node));}else if(tag==='UL'||tag==='OL'){output.push(...await list(node,depth));}else if(tag==='TABLE'){output.push(await table(node),new D.Paragraph({spacing:{after:100}}));}else if(tag==='PRE'){const lines=node.textContent.replace(/\n$/,'').split('\n');const st=runStyle(node.querySelector('code')||node),fill=color(style(node).backgroundColor)||'F6F8FA';for(const line of lines)output.push(new D.Paragraph({children:[new D.TextRun({text:line||' ',...st,font:'Consolas'})],shading:{type:D.ShadingType.CLEAR,fill},spacing:{after:0,line:260},indent:{left:120,right:120}}));output.push(new D.Paragraph({spacing:{after:60}}));}else if(tag==='BLOCKQUOTE'){const quoted=await blocks([...node.childNodes],depth);output.push(...quoted);}else if(tag==='HR'){output.push(new D.Paragraph({border:{bottom:{style:D.BorderStyle.SINGLE,size:4,color:'D0D7DE'}},spacing:{before:160,after:160}}));}else output.push(...await blocks([...node.childNodes],depth));}await flush();return output;}
const children=await blocks([...root.childNodes]);if(!children.length)children.push(new D.Paragraph(''));
const document=new D.Document({title,creator:'Markdown Studio',description:'Documento exportado de Markdown',styles:{default:{document:{run:{font:'Arial',size:24,color:'24292F'},paragraph:{spacing:{after:140,line:276}}}}},numbering:{config:numbering},sections:[{properties:{page:{size:page,margin:{top:marginTwip,right:marginTwip,bottom:marginTwip,left:marginTwip}}},children}]});return{blob:await D.Packer.toBlob(document),warnings:[...warnings]};
};
